### ISSUE TITLE
Could you not just have used peerJS does this already

### ISSUE THREAD

**Issue by The-Code-Monkey** [kyren/webrtc-unreliable#1]

**Comment by kyren** [comment]
peerJS only seems to be a library for normal browser <-> browser WebRTC (but more conveniently)?  I don't think that overlaps at all with this project?

**Comment by The-Code-Monkey** [comment]
What is the difference with your package as it seems to do the same thing and also webrtc is litterally for browser to browser communication

**Comment by kyren** [comment]
This project is for communication between a browser and a server process NOT running in a browser, and without depending on googles WebRTC library (which is a nontrivial subset of chromium).
