### ISSUE TITLE
connection outbound freezes for the client on a certain condition

### ISSUE THREAD

**Issue by cybersoulK** [kyren/webrtc-unreliable#22]
hi!
having a strange bug where the connection outbound freezes for the client, but inbound still works normally

after a certain condition, not easy to replicate, usually takes 10 minutes, and a big amount of packages sent at once, like 30 packets at once by the server to the client

statistics below is after it freezes, and within 1 second interval:

client:
incoming => new packets: 72, new bytes: 55033. 
outgoing => new packets: 18, new bytes: 755.

server:
 incoming => new packets: 0, new bytes: 0.
outgoing => new packets: 91, new bytes: 66947. 

i do have my own transport layer, and flush 300 times every second with a web worker (if there is any data), maybe that's why, and interrupts something in tokio::select?

```rust
let action = tokio::select! {

msg = server.recv() => msg.map(|msg| {
            
    (ServerAction::Receive(msg.message.to_vec()), msg.remote_addr)
}).ok(),

msg = rx_send_merge.recv() => msg.map(|(packet, remote_addr)| {
                        
     (ServerAction::Send(packet), remote_addr)
}),

msg = rx_flush.recv() => msg.map(|remote_addr| {
                        
     (ServerAction::Flush, remote_addr)
}),
```

**Comment by cybersoulK** [comment]
i also do have maximum MTU at 1100, could that be why?

**Comment by cybersoulK** [comment]
and it freezes just for one client, while other clients work normally, so less likely to be tokio::select! ?

**Comment by cybersoulK** [comment]
ok if i limit Flush at 60 fps on the server side (client side still 300fps flush), the server inbound freezing does not happen anymore (at least not as frequently).
 
60 fps + 300 fps, reloaded browser 100 times and no freezing.
300 fps + 300 fps = reloaded browser 20 times, 1 freeze

it could be that by interrupting server.recv() together with trying to send a burst 30-50 packets at a time makes irreversible damage to the inbound data channel

**Comment by cybersoulK** [comment]
Conclusion: after a amount of packages (10-20?), the client decides to start fragmenting packages outbound, which fell below the 1100 mtu (maybe 500 mtu?), 
and the webrtc-unreliable crate doesn't have a have to handle unfragmented packages yet

**Comment by kyren** [comment]
> webrtc-unreliable crate doesn't have a way to handle unfragmented packages yet

I'm very confused, that's not true? Unfragmented at what layer?

**Comment by cybersoulK** [comment]
> > webrtc-unreliable crate doesn't have a way to handle unfragmented packages yet
> 
> I'm very confused, that's not true? Unfragmented at what layer?

sorry, mean't to say fragmented, corrected the comment.
